### ISSUE TITLE
Selector prepending issue with Less-Component is generating wrong output

### ISSUE THREAD

**Issue by helgri** [KnisterPeter/Smaller#41]
The selector prepending behavior is not correct

``` scss
body{
    .root-chain1 & {
        .root-chain2& {
            color:red;
        }
    }
}
```

should compile to

``` css
.root-chain2.root-chain1 body{color:red}
```

but result is

``` css
.root-chain2 .root-chain1 body{color:red}
```

so the selector is broken.

This is a an LESS issue but has been already fix. So we need to update to LESS. It's correct in LESS 1.3.3 (client-js and node.js).
