### ISSUE TITLE
Smaller hangs on Windows

### ISSUE THREAD

**Issue by mohrph** [KnisterPeter/Smaller#53]
Client: smaller-ant-standalone-0.8.2

Smaller ant task hangs at the following line:

```
[smaller] 11288 [main] INFO de.matrixweb.nodejs.NodeJsExecutor - Execute node with json arg: "{\"indir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource7432001776695567263.dir\\input\",\"file\":\"_ui/extensions/js/app.json\",\"cwd\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\nodejs-v0.10.248203439111858252517.dir\",\"outdir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource7432001776695567263.dir\\output\",\"options\":{\"source-maps\":true,\"bare\":true,\"version\":\"1.0.0\"}}"
```

console output:

```
[smallerAlone] Reading config-file: C:\work\kunde\smaller.yml
[smallerAlone] Scanning C:\work\kunde\web\webroot
[smallerAlone] Scanning C:\work\kunde\web\webroot
[smallerAlone] 1038 [main] INFO de.matrixweb.smaller.pipeline.Pipeline - Executing processor lessjs
[smallerAlone] 1041 [main] INFO de.matrixweb.smaller.lessjs.LessjsProcessor - Setup lessjs (1.6.1) with node
[smallerAlone] 2264 [main] INFO de.matrixweb.nodejs.NodeJsExecutor - Execute node with json arg: "{\"indir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource2370321024179965496.dir\\input\",\"file\":\"_ui/extensions/css/app.less\",\"cwd\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\nodejs-v0.10.244491156648428432205.dir\",\"outdir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource2370321024179965496.dir\\output\",\"options\":{\"version\":\"1.0.0\"}}"
[smallerAlone] 3025 [main] INFO de.matrixweb.nodejs.NodeJsExecutor - node.js output:
[smallerAlone] OUT: 'Processing: C:\\Users\\someone\\AppData\\Local\\Temp\
[smallerAlone] OUT: ode-resource2370321024179965496.dir\\input\\_ui\\extensions\\css\\app.less'
[smallerAlone] OUT: 'Writing less result to C:\\Users\\someone\\AppData\\Local\\Temp\
[smallerAlone] OUT: ode-resource2370321024179965496.dir\\output\\_ui\\extensions\\css\\app.css'
[smallerAlone] 3104 [main] INFO de.matrixweb.smaller.javascript.JavaScriptExecutorFast - Try v8 executor
[smallerAlone] 3133 [main] INFO de.matrixweb.smaller.javascript.JavaScriptExecutorFast - Fallback to rhino executor
[smallerAlone] 3383 [main] INFO de.matrixweb.smaller.pipeline.Pipeline - Executing processor ycssmin
[smallerAlone] 3387 [main] INFO de.matrixweb.smaller.javascript.JavaScriptExecutorRhino - Executeing Rhino engine
[smallerAlone] 4092 [main] WARN de.matrixweb.smaller.resource.ProcessorUtil - Return processed result '/_ui/extensions/css/app.css'
[smallerAlone] 4096 [main] INFO de.matrixweb.smaller.pipeline.Pipeline - Executing processor coffeeScript
[smallerAlone] 4726 [main] INFO de.matrixweb.nodejs.NodeJsExecutor - Execute node with json arg: "{\"indir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource1335200192426879922.dir\\input\",\"file\":\"_ui/extensions/js/app.json\",\"cwd\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\nodejs-v0.10.247215162183992061911.dir\",\"outdir\":\"C:\\Users\\someone\\AppData\\Local\\Temp\\node-resource1335200192426879922.dir\\output\",\"options\":{\"source-maps\":true,\"bare\":true,\"version\":\"1.0.0\"}}"
```

Ant Task:

```
<taskdef name="smaller" 
classname="de.matrixweb.smaller.clients.ant.SmallerTask" 
classpath="/resources/ant/lib/smaller-ant-standalone-0.8.2.jar;/resources/ant/lib/snakeyaml-1.13.jar" />
<target name="smallerIt">
  <sequential>
    <smaller target="target/smaller" configFile="smaller.yml" />
  </sequential>
</target>
```

yml:

```
js:
        process: "../../../../web/webroot/extensions/js/app.js"

        files:
            folder:
                - "web/webroot"
            includes:
                - "**/*.coffee"
                - "**/*.js"
            excludes:
                - "**/*.jpg"

        test-files:
            folder:
            includes:
            excludes:

        processors:
            coffeeScript:                
                src: "extensions/js/app.json"
                options:
                    source-maps: true
                    bare: true
            merge:
                src: "extensions/js/app.json"
            closure:

        pipeline:
            - coffeeScript
            - merge
            - closure
```
